### ISSUE TITLE
Argument type not recognized for block Gf

### ISSUE THREAD

**Issue by gauthe** [TRIQS/triqs#103]
Hello,

I get an error in the CTQMC solver when I try to sum block Gf :

from pytriqs.applications.impurity_solvers.cthyb_matrix import Solver
S = Solver(beta = beta, gf_struct = [ ('up',[0]), ('down',[0]) ])
S.G <<= SemiCircular(2_t)
S.G0 <<= inverse(iOmega_n - t_*2 \* S.G)   # self-consistency relation (assume lattice == Bette))

I get :
Traceback (most recent call last):
  File "run_dmft.py", line 23, in <module>
    S.G0 <<= inverse(iOmega_n - t*_2 \* S.G)   # self-consistency relation (assume lattice == Bette))
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/block_gf.py", line 244, in **ilshift**
    for i,g in self:  g <<= A
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/gf_generic.py", line 214, in **ilshift**
    self.copy_from (lazy_expressions.eval_expr_with_context(e_t, A2) )
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/lazy_expressions.py", line 98, in eval_expr_with_context
    return f (_map(lambda e:eval_expr_with_context(eval_term, e) , expr.childs[1:]) ) 
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/lazy_expressions.py", line 98, in <lambda>
    return f (_map(lambda e:eval_expr_with_context(eval_term, e) , expr.childs[1:]) ) 
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/lazy_expressions.py", line 102, in eval_expr_with_context
    return ops[expr.tag](*map%28lambda e:eval_expr_with_context%28eval_term, e%29 , expr.childs%29) 
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/lazy_expressions.py", line 101, in <lambda>
    ops = { "+": lambda x, y: x + y, "-": lambda x, y: x - y, "_": lambda x, y: x \* y, "/": lambda x, y: x / y }
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/gf_generic.py", line 285, in **sub**
    return self.__sub_isub_impl(c,y,True)
  File "/scratch/gauthe/triqs/build/install/lib/python2.7/dist-packages/pytriqs/gf/local/gf_generic.py", line 271, in __sub_isub_impl
    raise RuntimeError, " argument type not recognized in -= for %s"%arg
RuntimeError:  argument type not recognized in -= for G

the code works if I do not use block Gf :
  for n,g0 in S.G0:
    g0 <<= inverse(iOmega_n - t**2 \* S.G[n])   # self-consistency relation (assume lattice == Bette))

**Comment by parcollet** [comment]
@mferrero : decide if you want to add the feature or close...

**Comment by parcollet** [comment]
- todo : add g[:] for blocks
- fix this in unstable.

**Comment by parcollet** [comment]
todo : fix is easy or discard.

**Comment by Wentzell** [comment]
Reproduce with 

``` python
from pytriqs.gf import *

G=GfImFreq(n_points = 5, beta=1.,statistic="Fermion", indices=[''])
G << iOmega_n

Ginv=G.copy()
Ginv << inverse(iOmega_n - 2. * G)
Ginv[:] = inverse(iOmega_n - 2. * G)

GBlock = BlockGf(name_list = ['up', 'do'], block_list = [G, G])
G2Bl = GBlock.copy()
G2Bl << inverse(iOmega_n - 2. * GBlock)
G2Bl[:] = inverse(iOmega_n - 2. * GBlock)

print Ginv.data
print G2Bl['up'].data
```

**Comment by parcollet** [comment]
Incompatible with previous API : 

G << x

is already 

for g in G: 
   g << x

G << inverse (omega_n - 2 * G1)
would require to flatten G1 implicitly.
Too complex, not very clear.
