### ISSUE TITLE
Read/Write gf fom/to hdf file

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#170]
Reading a self-energy (gf) from an hdf file and then storing it without any modification to a different hdf file with the following python code:

from pytriqs.gf.local import *
from pytriqs.archive import *
ar1 = HDFArchive('Sigma_test.h5','a')
S = ar1['Sigma']['Sigma_w']
ar2 = HDFArchive('Sigma_test_save.h5','a')
ar2.create_group('Sigma')
ar2['Sigma']['Sigma_w'] = S
del ar1
del ar2

gives the error:
/TRIQS/lib/python2.7/dist-packages/pytriqs/archive/hdf_archive.pyc in __setitem__(self, key, val)
    194             if (d=={}) : raise ValueError, "__reduce_to_dict__ returns an empty dict"
    195             SUB = HDFArchiveGroup(self,key)
--> 196             for n,v in d.items() : SUB[n] = v
    197             write_attributes(SUB)
    198         elif type(val)== numpy.ndarray : # it is a numpy

/TRIQS/lib/python2.7/dist-packages/pytriqs/archive/hdf_archive.pyc in __setitem__(self, key, val)
    159     #-------------------------------------------------------------------------
    160     def __setitem__(self,key,val) :
--> 161         key= self._key_cipher(key)# first look if key is a string or key
    162 
    163         if key in self.keys() :

/TRIQS/lib/python2.7/dist-packages/pytriqs/archive/hdf_archive.pyc in _key_cipher(self, key)
     93         if self.key_as_string_only : # for bacward compatibility
     94             if type(key) not in [ type('') , type(u'a')] :
---> 95                 raise KeyError, "Key must be string only !"
     96             return key
     97         r = repr(key)

KeyError: 'Key must be string only !'

**Comment by betzin** [comment]
I have the same or at least a similar problem.
I do 2 DMFT iterations. In the first iteration everything runs fine. In the second one the code stops at the step where S.Sigma_iw and S.G_iw is written to the HDFarchive with the message:

Traceback (most recent call last):
 File "dmft.py", line 308, in <module>
   ar['Sigma_iw']   = S.Sigma_iw
 File "/usr/users/iff_th1/betzin/DMFT/TRIQS-Fleur/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 196, in __setitem__
   for n,v in d.items() : SUB[n] = v
 File "/usr/users/iff_th1/betzin/DMFT/TRIQS-Fleur/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 161, in __setitem__
   key= self._key_cipher(key)# first look if key is a string or key
 File "/usr/users/iff_th1/betzin/DMFT/TRIQS-Fleur/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 95, in _key_cipher
   raise KeyError, "Key must be string only !"
KeyError: 'Key must be string only !'

**Comment by pascaldelange** [comment]
I am having the same problem. 
When I touch an object in an HDF archive that has been touched before in the script I get the following error message:
Traceback (most recent call last):
  File "PA_model.py", line 326, in <module>
    ar['SigmaF'] = Sigma
  File "/home/delange/sources/TRIQS_1.2_cthyb_debug/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 196, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/home/delange/sources/TRIQS_1.2_cthyb_debug/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 161, in __setitem__
    key= self._key_cipher(key)# first look if key is a string or key
  File "/home/delange/sources/TRIQS_1.2_cthyb_debug/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 95, in _key_cipher
    raise KeyError, "Key must be string only !"
KeyError: 'Key must be string only !'

**Comment by MHarland** [comment]
I had the same problem and although I don't know its origin I can provide a little workaround that has made all my all scripts work again:

change line 94 in hdf_archive.py to
```python
if type(key) not in [ type('') , type(u'a'), numpy.string_]:
```
change line 92 in block_gf.py to
```python
for i,g in self: g.name = "%s_%s"%(str(self.name),i) if self.name else '%s'%(i,)
```

**Comment by mzingl** [comment]
Hi,
the issue is actually caused by reading the attribute block_names as a numpy array from the hdf file. However, this array of numpy.string_  is never converted to str, which should be done e.g. after line 88 in hdf_archive_basic_layer_h5py.py by
try:
if v.dtype.name.startswith('string') : return map(str,v)
    except AttributeError:
        pass

**Comment by leopo** [comment]
I still get this error running on montblanc. When after reading old Sigma and mixing it with new one the result is being written to h5, the following error appears

Traceback (most recent call last):
  File "Fe-hcp.py", line 154, in <module>
    ar['Sigma'] = S.Sigma_iw
  File "/home/leonid/TRIQS1.2/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 196, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/home/leonid/TRIQS1.2/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 161, in __setitem__
    key= self._key_cipher(key)# first look if key is a string or key
  File "/home/leonid/TRIQS1.2/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 95, in _key_cipher
    raise KeyError, "Key must be string only !"
KeyError: 'Key must be string only !'

I use the most recent TRIQS version, the line of M. Zingl is in hdf_archive_basic_layer_h5py.py, but it does not seem to help. On weiss the same code runs OK.
