### ISSUE TITLE
Umatrix in the tutorial of Ce

### ISSUE THREAD

**Issue by xiaoyukaka** [TRIQS/triqs#179]
Dear developers,
I have performed the calculations of Ce employing the Hubbard-I approximation with triqs V1.0. When i import Hubbard-I solver by 
'from pytriqs.applications.impurity_solvers.hubbard_I.hubbard_solver import Solver'
===========================================================================
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xykk/software/triqs/install_triqs/lib/python2.7/dist-packages/pytriqs/applications/impurity_solvers/hubbard_I/__init__.py", line 26, in <module>
    from hubbard_solver import Solver
  File "/home/xykk/software/triqs/install_triqs/lib/python2.7/dist-packages/pytriqs/applications/impurity_solvers/hubbard_I/hubbard_solver.py", line 24, in <module>
    from pytriqs.applications.dft.U_matrix import Umatrix
ImportError: cannot import name Umatrix
===========================================================================
I can find the U_matrix.py and U_matrix.pyc, but it cannot import.

**Comment by xiaoyukaka** [comment]
I found it's the same reason that I could not complete the test during the installation of Hubbard-I. The error information is provided in /hubbardI/build/test/hubbard_output.err.
 How to solve it?

**Comment by tayral** [comment]
Dear xiaoyukaka,
Please post issues referring to HubbardI in the right place, namely at: https://github.com/TRIQS/hubbardI/issues.
Thanks

**Comment by tayral** [comment]
This issue was moved to TRIQS/hubbardI#1
