### ISSUE TITLE
Hilbert example broken

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#200]
The example script for the Hilbert transform is broken:

```
from pytriqs.lattice.tight_binding import *
from pytriqs.dos import HilbertTransform
from pytriqs.gf.local import GfImFreq

# Define a DOS (here on a square lattice)
BL = BravaisLattice(units = [(1,0,0) , (0,1,0) ], orbital_positions= [(0,0,0)] )
t   = -1.00                # First neighbour Hopping
tp  =  0.0*t               # Second neighbour Hopping
hop= {  (1,0) :  [[ t]],
        (-1,0):  [[ t]],
        (0,1) :  [[ t]],
        (0,-1):  [[ t]],
        (1,1) :  [[ tp]],
        (-1,-1):  [[ tp]],
        (1,-1):  [[ tp]],
        (-1,1):  [[ tp]]}

TB = TightBinding (BL, hop)
d = dos(TB, n_kpts= 500, n_eps = 101, name = 'dos')[0]

#define a Hilbert transform
H = HilbertTransform(d)

#fill a Green function
G = GfImFreq(indices = ['up','down'], beta = 20)
Sigma0 = GfImFreq(indices = ['up','down'], beta = 20); Sigma0.zero()
G << H(Sigma = Sigma0,mu=0.)
```
yields:
```
Starting on 1 Nodes at : 2015-02-16 15:50:58.712014
Traceback (most recent call last):
  File "hilbert.py", line 27, in <module>
    G << H(Sigma = Sigma0,mu=0.)
  File "/home/tayral/Work/TRIQS/install/lib/python2.7/dist-packages/pytriqs/dos/hilbert_transform.py", line 177, in __call__
    HT(result)
  File "/home/tayral/Work/TRIQS/install/lib/python2.7/dist-packages/pytriqs/dos/hilbert_transform.py", line 123, in HT
    if Sigma_fnt : assert len(inspect.getargspec(Sigma)[0]) ==1, "Sigma function is not of the correct type. See Documentation"
  File "/usr/lib/python2.7/inspect.py", line 816, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: gf_view is not a Python function
```
This was working e.g at commit #3288127

**Comment by parcollet** [comment]
@mferrero : isn't it consequence of your patch to make gf a function in python ?

**Comment by mferrero** [comment]
Yes it is... ``SumkDiscrete`` will also be affected. We have to decide between two things: 1) Let gf's be callable objects but then ``HilbertTransform`` and ``SumkDiscrete`` have to be changed to specify when we want to use a self-energy that is a function of energy 2) Let these two classes as they are now and use a special evaluator for the gf's. I would vote for 1)

**Comment by parcollet** [comment]
What is the pb ? sumK recognize that G is callable, hence believe it is a function of energy returning a function ? 
Which special evaluator ?
Indeed, the best is to have a clean API for G, and change the old lattice class accordingly, i.e.1)

**Comment by mferrero** [comment]
OK, I'll do it asap.

**Comment by mferrero** [comment]
Should be fixed. @tayral: can you check as well?

**Comment by tayral** [comment]
it works!
