### ISSUE TITLE
hdf_archive issue on a recent cluster

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#251]
I am seeing an error when running some of the tests on one of the clusters I use (montblanc) after upgrading to the latest TRIQS version. Note that the tests run on other clusters (weiss) with no problems.

```
The following tests FAILED:
	131 - gf_init (Failed)
	132 - gf_base_op (Failed)
	134 - pade (Failed)
	139 - wrap_a (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Looking at the individual tests, these are the messages.
```
[16x64pcmontblanc1 build] cat test/pytriqs/base/gf_init_output.err 
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "/home/pseth/SOURCES/TRIQS/triqs/build/pytriqs/archive/hdf_archive.py", line 186, in __setitem__
    val.__write_hdf5__(self._group,key)
TypeError: Internal error : invalid id from h5py !

[16x64pcmontblanc1 build] cat test/pytriqs/base/gf_base_op_output.err 
Traceback (most recent call last):
  File "<stdin>", line 132, in <module>
  File "/home/pseth/SOURCES/TRIQS/triqs/build/pytriqs/archive/hdf_archive.py", line 196, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/home/pseth/SOURCES/TRIQS/triqs/build/pytriqs/archive/hdf_archive.py", line 186, in __setitem__
    val.__write_hdf5__(self._group,key)
TypeError: Internal error : invalid id from h5py !
```

This problem occurs before commit 3da2875. I emphasize that this occurs on one of the clusters -- it this a dependency issue for h5py?

**Comment by parcollet** [comment]
Hi, 
What is your detected hdf5 ? (-> cmake output ?).
This is the typical error when h5py is linked to a different hdf5 lib compared to the triqs c++ code.
In [4]: h5py.version.hdf5_version
Out[4]: '1.8.13'
(it is linked to the anaconda version of hdf5, which is 1.8.13, while the C++ lib is called hdf5_18/1.8.12 ).

We should add a simple security for this ....

Olivier

**Comment by pseth** [comment]
Ok, I fixed it. Yes, it would be good to add a check here. The version printed out by cmake is the c++ version, correct?

**Comment by santoshkumarradha** [comment]
Installing triqs in a fresh conda environment with conda forge creates the same error.
