### ISSUE TITLE
"TypeError: can only concatenate tuple (not "list") to tuple" when trying to open HDF5 archive

### ISSUE THREAD

**Issue by pbakalov** [TRIQS/triqs#267]
I get the following when I try retrieving a GfImFreq from an hdf archive (produced by v. 1.0) in version 1.2:

```
Traceback (most recent call last):
  File "mwe_bulk.py", line 17, in <module>
    Sigma = A['Self_energy']
  File "/Users/fun/triqs/build/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 222, in __getitem__
    return self.__getitem1__(key,self._reconstruct_python_objects)
  File "/Users/fun/triqs/build/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 264, in __getitem1__
    return r_class.__factory_from_dict__(key,values)
  File "/Users/fun/triqs/build/install/lib/python2.7/site-packages/pytriqs/gf/local/block_gf.py", line 203, in __factory_from_dict__
    'name']) == sorted(d.keys())),  "Reload mismatch: the indices and the group names do not corresponds"
TypeError: can only concatenate tuple (not "list") to tuple
```

The full code is:
```
from pytriqs.gf.local import *
from pytriqs.operators import *
from pytriqs.archive import *

import sys, pytriqs.version as version
from pytriqs.plot.mpl_interface import *
plt.ion()

filename = "bulk2.h5"

A = HDFArchive(filename,'r')
n_loops = A["other"]["n_loops_done"]
beta = A["other"]["beta"]
print "n_loops: ", n_loops
print "beta: ", beta

Sigma = A['Self_energy']
```

and the .h5 file can be found here: https://github.com/pbakalov/triqs_misc/blob/master/bulk2.h5

What am I missing?

(working on OS X Yosemite)

**Comment by parcollet** [comment]
@krivenko 
Is it simply a consequence of c55fe744abb0e0e7fb31f44380fa787ad47453e5
which was not caught by tests ?

**Comment by krivenko** [comment]
>  Is it simply a consequence of c55fe74 which was not caught by tests ?

No, it's not.
Indices of `BlockGf` in the said h5 file are stored as one string `"('up', 'down')"` (older format?)
This string is obviously reconstructed into a tuple, then a concatenation with a list fails.

**Comment by parcollet** [comment]
@mferrero : need the conversion script for archive ?

**Comment by parcollet** [comment]
Shall we close this ? 
Or do we need to publish a conversion script ? @mferrero 
Recent versions =>1.3 do backward compatibility automatically.

**Comment by Wentzell** [comment]
Fixed. `BlockGf.__factory_from_dict__` now reads block names from the modern `block_names` field when present, and otherwise falls back to the legacy `indices` string (`eval(d.pop('indices'))`) for old-format archives like the one here. The buggy `tuple + list` concatenation that produced this `TypeError` was removed and replaced by a `set(keys).issubset(...)` check, so reading these older archives works. Closing as resolved.
