### ISSUE TITLE
"ImportError: cannot import name namedtuple" while building comparison_tests_wrap

### ISSUE THREAD

**Issue by opeil** [TRIQS/triqs#301]
'master' branch [69bd67a9]: fails to build with the error message below.
 The culprit is a module 'bisect.py' that has the same name as a built-in module required by 'collections'.
  The workaround right now is to rename 'bisect.py' in 'build/pytriqs/utility/' to something else before building and rename it back afterwards.

```
Traceback (most recent call last):
  File "/home/opeil/Codes/triqs/triqs1.4/build1.4/pytriqs/utility/comparison_tests_desc.py", line 1, in <module>
    from wrap_generator import *
  File "/home/opeil/Codes/triqs/triqs1.4/build1.4/tools/cpp2py/wrap_generator.py", line 4, in <module>
    from mako.template import Template
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 10, in <module>
    from mako.lexer import Lexer
  File "/usr/lib/python2.7/dist-packages/mako/lexer.py", line 10, in <module>
    from mako import parsetree, exceptions, util
  File "/usr/lib/python2.7/dist-packages/mako/parsetree.py", line 9, in <module>
    from mako import exceptions, ast, util, filters
  File "/usr/lib/python2.7/dist-packages/mako/exceptions.py", line 10, in <module>
    from mako import util
  File "/usr/lib/python2.7/dist-packages/mako/util.py", line 24, in <module>
    import collections
  File "/usr/lib/python2.7/collections.py", line 12, in <module>
    import heapq as _heapq
  File "/usr/lib/python2.7/heapq.py", line 134, in <module>
    import bisect
  File "/home/opeil/Codes/triqs/triqs1.4/build1.4/pytriqs/utility/bisect.py", line 22, in <module>
    import scipy.optimize
  File "/usr/lib/python2.7/dist-packages/scipy/__init__.py", line 78, in <module>
    from numpy import show_config as show_numpy_config
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing import Tester
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/lib/python2.7/unittest/__init__.py", line 58, in <module>
    from .result import TestResult
  File "/usr/lib/python2.7/unittest/result.py", line 9, in <module>
    from . import util
  File "/usr/lib/python2.7/unittest/util.py", line 2, in <module>
    from collections import namedtuple, OrderedDict
ImportError: cannot import name namedtuple
make[2]: *** [pytriqs/utility/comparison_tests_wrap.cpp] Erreur 1
make[1]: *** [pytriqs/utility/CMakeFiles/python_wrap_comparison_tests.dir/all] Erreur 2
make: *** [all] Erreur 2
```

**Comment by parcollet** [comment]
The best would be to simple rename bisect in triqs ...
what is this module doing ?

**Comment by pseth** [comment]
I would call it triqs_bisect. It basically is a wrapper around scipy's bisect, and is meant to replace dichotomy which I had some trouble with a long time ago.

**Comment by parcollet** [comment]
why don't we use scipy bisect ??

**Comment by pseth** [comment]
We do, but we need to determine the bounds which scipy.bisect needs (if I remember correctly).

**Comment by pseth** [comment]
Or bound_and_bisect. I'll rename to that.
