### ISSUE TITLE
compilation fails

### ISSUE THREAD

**Issue by gkraberger** [TRIQS/triqs#324]
Hi,

when compiling TRIQS (7fac73cfdd3c2c7147afdc626a83002810bd7008) in parallel mode with >4 cores (e.g. make -j8), I get the following error:

```
[  0%] [  0%] [  0%] [  1%] Generating ../py_copy_test.tar
Generating ../py_copy.tar
Generating ../tools_copy.tar
Building CXX object triqs/test_tools/CMakeFiles/gtest.dir/gtest-all.cc.o
[  1%] Built target py_copy_test
[  1%] Built target py_copy
[  1%] Built target tools_copy
[  2%] [  2%] [  2%] [  2%] Generating block_matrix_wrap.cpp, ../../include/triqs/py_converters/block_matrix.hpp
Generating multivar_wrap.cpp, ../../../include/triqs/py_converters/multivar.hpp
Generating gf_wrap.cpp, ../../../include/triqs/py_converters/gf.hpp
Generating comparison_tests_wrap.cpp, ../../include/triqs/py_converters/comparison_tests.hpp
Traceback (most recent call last):
  File "/home/lv70759/gkraberger/progs/TRIQS_complex/triqs.build/pytriqs/gf/local/multivar_desc.py", line 7, in <module>
    module.use_module('gf')
  File "/home/lv70759/gkraberger/progs/TRIQS_complex/triqs.build/tools/cpp2py/wrap_generator.py", line 774, in use_module
    if not f : raise RuntimeError, "Cannot find the module %s.\n  ... module_path_list = %s"%(modulename, self.module_path_list)
RuntimeError: Cannot find the module gf.
  ... module_path_list = ['/home/lv70759/gkraberger/progs/TRIQS_complex/triqs.build/include/triqs/py_converters/']
make[2]: *** [pytriqs/gf/local/multivar_wrap.cpp] Error 1
make[1]: *** [pytriqs/gf/local/CMakeFiles/python_wrap_multivar.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Built target python_wrap_comparison_tests
[  2%] Built target python_wrap_block_matrix
[  2%] Built target python_wrap_gf
Linking CXX shared library libgtest.so
[  2%] Built target gtest
make: *** [all] Error 2
```

With 4 or less cores it works. (I tried on machines with 4 and 32 cores, both show the same behaviour.)

Best
Gernot

**Comment by pseth** [comment]
I see the same thing. A guess, but it is a problem of ordering the files in a sensible way that fits the chronological order of compilation and imports? Do we need a type of mpi barrier?

**Comment by krivenko** [comment]
I fixed a similar issue in the applications by commit 37d15a47f1ca2869c74e1517740ae08d5f426eda.
It looks like a variant of that fix must be applied to the library itself.
