### ISSUE TITLE
Triqs element-wise vector operations missing?

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#410]
Hi, I am trying to do basic element-wise operations with `triqs::arrays::vector<double>` such as adding/subtracting a double constant. I.e.:

```c++
%%triqs             
#include <triqs/arrays.hpp>
using namespace triqs::arrays;

void vector_operations() {
    int N = 5;
    
    vector<double> v(N);
    v() = 1.234;
    
    vector<double> x(N);
    
    // Involved calculation of: x = 0.5*(v - 1.)
    x() = v;
    x += -1.;
    x *= 0.5;
    
    // Would like to write this, but (v - 1.) is not implemented
    x = 0.5*(v - 1.0);
}
```
this produces the error:
```
RuntimeError: Clang reports the following errors in parsing
 file ./ext.cpp line 21 col 16
invalid operands to binary expression ('vector<double>' and 'double')
```
see below for the full error message.

Are element-wise operations not supported for the `triqs::arrays::vector<T>`? What is the correct way of doing this?

```
----------------------------c++2py error ----------------------------
Welcome to the wrapper desc file generator of TRIQS, based on libclang !
Parsing the C++ file (may take a few seconds) ...
... done. 
Extracting ...
Traceback (most recent call last):
  File "/Users/hugstr/apps/triqs_devel/bin/c++2py.py", line 93, in <module>
    analyze_filter = analyze_filter)
  File "/Users/hugstr/apps/triqs_devel/bin/clang_parser.py", line 416, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file ./ext.cpp line 21 col 16
invalid operands to binary expression ('vector<double>' and 'double')
... Your code must compile before using clang-parser !

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-f20c4f29d6f6> in <module>()
----> 1 get_ipython().run_cell_magic(u'triqs', u'            ', u'#include <triqs/arrays.hpp>\nusing namespace triqs::arrays;\n\nvoid vector_operations() {\n    int N = 5;\n    \n    vector<double> v(N);\n    v() = 1.234;\n    \n    vector<double> x(N);\n    \n    // Involved calculation of: x = 0.5*(v - 1.)\n    x() = v;\n    x += -1.;\n    x *= 0.5;\n    \n    // Would like to write this, but (v - 1.) is not implemented\n    x = 0.5*(v - 1.0);\n}')

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2113             magic_arg_s = self.var_expand(line, stack_depth)
   2114             with self.builtin_trap:
-> 2115                 result = fn(magic_arg_s, cell)
   2116             return result
   2117 

<decorator-gen-123> in triqs(self, line, cell)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/magic.pyc in triqs(self, line, cell)
    144             only_list = ','.join(args.only)
    145             only_list = (" --only " + only_list) if only_list else ''
--> 146             execute(cpp2py_bin + " ./ext.cpp -p -m ext -o ext" + only_list, "c++2py")
    147 
    148             # Call the wrapper generator

/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/magic.pyc in execute(command, message)
    137                 except subprocess.CalledProcessError as E :
    138                    print_out ( message + " error ", E.output)
--> 139                    raise RuntimeError, "Error"
    140                 if args.verbosity>0:
    141                    print_out(message, out)

RuntimeError: Error
```

**Comment by krivenko** [comment]
Hi Hugo,
Here is what the documentation has to say
```
The matrix and vector are very similar to an array of dimension 2 and 1 respectivily,
except for their algebra. Array form an array algebra, where operation are done element-wise,
while matrix and vector form the usual algebra and vector space of linear algebra.
```
https://triqs.ipht.cnrs.fr/1.x/reference/arrays/containers/regular.html

I guess you would have to use `array<double,1>` in your example.

**Comment by Wentzell** [comment]
Hey,

Indeed this operation exists only with the array.

With a small performance penalty you can create a temporary view to get the operation you want

```c++
x = 0.5 * (array_view<double,1>(v) - 1.0);
```
