### ISSUE TITLE
How to slice/assign from higher rank arrays using `clef::placeholder`?

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#411]
Hi, I am trying to slice/assign higher rank arrays to lower rank ones, but can not get `triqs::clef::placeholder` to work for this case. 

Consider this example (in jupyter-notebook format)

```
%reload_ext pytriqs.magic
```
```c++
%%triqs             
#include <triqs/arrays.hpp>
using namespace triqs::arrays;

void array_slice_for_loop() {
    int N = 5;
    array<double, 2> r(N, 2); r() = 1.234;
    vector<double> x(N), y(N);
    
    // set x and y from slices of r
    // verbose version
    
    for( auto idx : range(x.size()) ) {
        x(idx) = r(idx, 0);
        y(idx) = r(idx, 1);
    }
    std::cout << "x = " << x << "\n";
    std::cout << "y = " << y << "\n";
}
```
```python
array_slice_for_loop()
```
```
x = [1.234,1.234,1.234,1.234,1.234]
y = [1.234,1.234,1.234,1.234,1.234]
```
now if I try to do the same with placeholders 

```c++
%%triqs             
#include <triqs/arrays.hpp>
#include <triqs/clef.hpp>
using namespace triqs::arrays;
using namespace triqs::clef;

void vector_operations() {
    int N = 5;
    array<double, 2> r(N, 2); r() = 1.234;
    vector<double> x(N), y(N);
    
    // set x and y from slices of r
    
    // clef not supported?
    placeholder<0> i_;
    x(i_) = r(i_, 0);
    y(i_) = r(i_, 1);
}
```
I get the error:

```
RuntimeError: Clang reports the following errors in parsing
 file ./ext.cpp line 18 col 11
overload resolution selected deleted operator '=' file ./ext.cpp line 19 col 11
overload resolution selected deleted operator '='
```
see below for the full error output. 

What is wrong with this clef expression? How can I do this type of assignments? Can I even make views `x` and `y` without having to copy data?

```
----------------------------c++2py error ----------------------------
Welcome to the wrapper desc file generator of TRIQS, based on libclang !
Parsing the C++ file (may take a few seconds) ...
... done. 
Extracting ...
Traceback (most recent call last):
  File "/Users/hugstr/apps/triqs_devel/bin/c++2py.py", line 93, in <module>
    analyze_filter = analyze_filter)
  File "/Users/hugstr/apps/triqs_devel/bin/clang_parser.py", line 416, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file ./ext.cpp line 18 col 11
overload resolution selected deleted operator '=' file ./ext.cpp line 19 col 11
overload resolution selected deleted operator '='
... Your code must compile before using clang-parser !

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-ef9f46e5f466> in <module>()
----> 1 get_ipython().run_cell_magic(u'triqs', u'            ', u'#include <triqs/arrays.hpp>\n#include <triqs/clef.hpp>\nusing namespace triqs::arrays;\nusing namespace triqs::clef;\n\nvoid vector_operations() {\n    int N = 5;\n    array<double, 2> r(N, 2); r() = 1.234;\n    vector<double> x(N), y(N);\n    \n    // set x and y from slices of r\n    \n    // clef not supported?\n    placeholder<0> i_;\n    x(i_) = r(i_, 0);\n    y(i_) = r(i_, 1);\n}')

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_cell_magic(self, magic_name, line, cell)
   2113             magic_arg_s = self.var_expand(line, stack_depth)
   2114             with self.builtin_trap:
-> 2115                 result = fn(magic_arg_s, cell)
   2116             return result
   2117 

<decorator-gen-122> in triqs(self, line, cell)

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/magic.pyc in triqs(self, line, cell)
    144             only_list = ','.join(args.only)
    145             only_list = (" --only " + only_list) if only_list else ''
--> 146             execute(cpp2py_bin + " ./ext.cpp -p -m ext -o ext" + only_list, "c++2py")
    147 
    148             # Call the wrapper generator

/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/magic.pyc in execute(command, message)
    137                 except subprocess.CalledProcessError as E :
    138                    print_out ( message + " error ", E.output)
--> 139                    raise RuntimeError, "Error"
    140                 if args.verbosity>0:
    141                    print_out(message, out)

RuntimeError: Error
```

**Comment by parcollet** [comment]
The syntax is 
x(i_) << r(i_, 0);
    y(i_) << r(i_, 1);

<< , not =
