### ISSUE TITLE
Multplication of Green's function with complex scalar

### ISSUE THREAD

**Issue by gkraberger** [TRIQS/triqs#437]
Hi,

In the unstable branch, the multiplication of Green's function objects with complex scalars throws an error:

```
Traceback (most recent call last):
  File "complex_scalar.py", line 9, in <module>
    A_iw << 1.0j*G_iw
  File "/temp/AG-CMS/TRIQS/complex/new_debian/unstable/lib/python2.7/dist-packages/pytriqs/gf/gf.py", line 452, in __rmul__
    def __rmul__(self,x): return self.__mul__(x)
  File "/temp/AG-CMS/TRIQS/complex/new_debian/unstable/lib/python2.7/dist-packages/pytriqs/gf/gf.py", line 449, in __mul__
    c *= y
  File "/temp/AG-CMS/TRIQS/complex/new_debian/unstable/lib/python2.7/dist-packages/pytriqs/gf/gf.py", line 444, in __imul__
    if self._singularity : self._singularity *= arg
TypeError: unsupported operand type(s) for *=: 'pytriqs.gf.singularities.TailGf' and 'complex'
```

It used to work in version 1.4.

Test script:
```
# for comparison with 1.4 I use the old style                                  
from pytriqs.gf.local import *                                             
                                                                           
G_iw = GfImFreq(beta=40,indices=[0,1])                                     
G_w = GfReFreq(window=(-3,3),indices=[0,1])                                
                               
A_iw = G_iw.copy()
A_w =G_w.copy()                                            
A_iw << 1.0j*G_iw                                                           
A_w << 1.0j*G_w
```

Motivation/possible use cases for multiplication of complex scalars with GF:
- Calculating the spectral function A = i (G-G^dagger)/2pi
- calculating hybridization functions as Delta_ij = sum_b V_bi^* V_bj / (w - E_b) where V_bi^* V_bj is, in general, a complex scalar.

**Comment by parcollet** [comment]
Sure, it is a regression in unstable.
