### ISSUE TITLE
Unary + operators breaks clef expressions

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#440]
It seems like not all unary operators are compatible with clef expressions. Out of the two cases

```c++
gout[closest_mesh_pt(t)](a, b) << + g(t)(a, b) - g(t)(a, b); // unary + operator
```
and

```c++
gout[closest_mesh_pt(t)](a, b) << - g(t)(a, b) + g(t)(a, b);
```
only the second case compiles.

This behaviour is very confusing and unexpected. See below for a full working example.

Best, Hugo

----

```c++
%%triqs             

#include <triqs/gfs.hpp>
#include <triqs/clef.hpp>
using namespace triqs::gfs;
using namespace triqs::clef;

placeholder<0> a;
placeholder<1> b;
        
void test(gf_view<imtime, matrix_valued> g, gf_view<imtime, matrix_valued> gout) {
    for (auto const &t : g.mesh()) {
        gout[closest_mesh_pt(t)](a, b) << + g(t)(a, b) - g(t)(a, b); // unary + operator
    }
}
```

gives 

```
----------------------------c++2py error ----------------------------
Welcome to the wrapper desc file generator of TRIQS, based on libclang !
Parsing the C++ file (may take a few seconds) ...
... done. 
Extracting ...
Traceback (most recent call last):
  File "/Users/hugstr/apps/triqs_devel/bin/c++2py.py", line 93, in <module>
    analyze_filter = analyze_filter)
  File "/Users/hugstr/apps/triqs_devel/bin/clang_parser.py", line 416, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file ./ext.cpp line 15 col 43
invalid argument type 'decltype(make_expr_call(std::move(*this), std::forward<triqs::clef::_ph<0> &>(args), std::forward<triqs::clef::_ph<1> &>(args)))' (aka 'triqs::clef::expr<triqs::clef::tags::function, triqs::arrays::matrix_expr<triqs::utility::tags::plus, triqs::arrays::matrix_expr<triqs::utility::tags::multiplies, triqs::arrays::_scalar_wrap<double, false>, triqs::arrays::matrix_const_proxy<const triqs::arrays::array_view<std::__1::complex<double>, 3, void, false, false> &, long> >, triqs::arrays::matrix_expr<triqs::utility::tags::multiplies, triqs::arrays::_scalar_wrap<double, false>, triqs::arrays::matrix_const_proxy<const triqs::arrays::array_view<std::__1::complex<double>, 3, void, false, false> &, long> > >, triqs::clef::_ph<0>, triqs::clef::_ph<1> >') to unary expression
... Your code must compile before using clang-parser !
```

while 
```c++
%%triqs             

#include <triqs/gfs.hpp>
#include <triqs/clef.hpp>
using namespace triqs::gfs;
using namespace triqs::clef;

placeholder<0> a;
placeholder<1> b;
        
void test(gf_view<imtime, matrix_valued> g, gf_view<imtime, matrix_valued> gout) {
    for (auto const &t : g.mesh()) {
        gout[closest_mesh_pt(t)](a, b) << - g(t)(a, b) + g(t)(a, b);
    }
}
```
compiles nicely

**Comment by parcollet** [comment]
Yes, I did not code the + unary, I thought it was a bit useless ...

**Comment by parcollet** [comment]
Should I add other unary ops ?
