### ISSUE TITLE
MatsubaraToLegendre broken "Cannot convert to triqs::gfs::nothing"

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#459]
The initialisation example for a Legendre Green's function using a imaginary frequency Green's function is broken. Running the second example in

https://triqs.ipht.cnrs.fr/1.x/reference/gfs/py/transforms.html

```python
from pytriqs.gf.local import *
from pytriqs.plot.mpl_interface import oplot

# A Green's function on the Matsubara axis set to a semicircular
gw = GfImFreq(indices = [1], beta = 50)
gw << SemiCircular(half_bandwidth = 1)

# Create a Legendre Green's function with 40 coefficients
# initialize it from gw and plot it
gl = GfLegendre(indices = [1], beta = 50, n_points = 40)
gl << MatsubaraToLegendre(gw)
oplot(gl, '-o')
```
crashes and burns, saying
```
Traceback (most recent call last):
  File "triqs_bug.py", line 11, in <module>
    gl << MatsubaraToLegendre(gw)
  File "/Users/.../lib/python2.7/site-packages/pytriqs/gf/gf.py", line 375, in __lshift__
    self << lazy_expressions.LazyExpr(A)
  File "/Users/../lib/python2.7/site-packages/pytriqs/gf/gf.py", line 373, in __lshift__
    self.copy_from (lazy_expressions.eval_expr_with_context(e_t, A2) )
  File "/Users/.../lib/python2.7/site-packages/pytriqs/gf/lazy_expressions.py", line 95, in eval_expr_with_context
    if expr.tag == "T": return eval_term(expr.childs[0]) #eval the terminals
  File "/Users/.../lib/python2.7/site-packages/pytriqs/gf/gf.py", line 371, in e_t
    x(tmp)
  File "/Users/.../lib/python2.7/site-packages/pytriqs/gf/descriptors.py", line 219, in __call__
    G2.set_from_imfreq(self.G)
  File "/Users/.../lib/python2.7/site-packages/pytriqs/gf/gf.py", line 57, in _
    return a(self, *args, **kw)
TypeError: Error: no suitable C++ overload found in implementation of function gf_fnt.set_from_imfreq

 set_from_imfreq(gf_view<legendre,matrix_valued> gl, gf_view<imfreq,matrix_valued> gw) -> void 
 failed with the error : 
  Cannot convert to triqs::gfs::nothing : can only convert None

 set_from_imfreq(gf_view<legendre,matrix_valued> gl, gf_view<imfreq,matrix_valued> gw) -> void 
 failed with the error : 
  Cannot convert to triqs::gfs::nothing : can only convert None
```

**Comment by parcollet** [comment]
Todo : improve error message in conversion of gf.

**Comment by parcollet** [comment]
Fixed.
   - In case of a similar problem, improve the error messages
      for the Py -> C++ convertion of gf
    - E.g. in the case of the issue, the message would now say  :
    
    ---------
    
    TypeError: Error: no suitable C++ overload found in implementation of function gf_fnt.set_from_imfreq
    
     set_from_imfreq(gf_view<legendre,matrix_valued> gl, gf_view<imfreq,matrix_valued> gw) -> void
     failed with the error :
      Cpp2py converter: Python to C++ :
      ... Conversion of a gf from Python to C++ triqs::gfs::gf_view<triqs::gfs::legendre, triqs::gfs::matrix_valued>
      ... Cannot convert the singularity of gf from Python type : pytriqs.gf.singularities.TailGf to the C++ type triqs::gfs::nothing

**Comment by parcollet** [comment]
@Wentzell : FYI
