### ISSUE TITLE
Segfault when using yep: bug in make_tail_view_from_data?

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#473]
Hi,
I am using yep to profile a pytriqs script:
```python
from pytriqs.gf import *
mu = 1.5 
e_h = 0.5 
G0_iw = GfImFreq(beta = 200., indices = [0,1])
G0_iw[0,0] = iOmega_n + mu -  (inverse(iOmega_n -e_h)  + inverse(iOmega_n + e_h))
```
The script runs without problem when just using pytriqs only, but issuing
```
pytriqs -myep -v script.py
```
yields a segfault. This segfault seems to originate from the singularities. Here is the gdb backtrace:
```bash
(gdb) bt
#0  0x00007ffff7825428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff782702a in __GI_abort () at abort.c:89
#2  0x00007ffff552d738 in _Unwind_Resume () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#3  0x00007fffe258ba35 in triqs::arrays::indexmap_storage_pair<triqs::arrays::indexmaps::cuboid::map<1, void>, triqs::arrays::storages::shared_block<std::complex<double>, false>, void, false, true, triqs::arrays::Tag::array_view>::indexmap_storage_pair(_object*, bool, char const*) ()
   from /home/tayral/Work/TRIQS_1.6/install_gcc7/lib/python2.7/dist-packages/pytriqs/gf/singularities.so
#4  0x00007fffe2561445 in int converter_for_parser_view_type<triqs::arrays::array_view<std::complex<double>, 1, void, false, false> >(_object*, triqs::arrays::array_view<std::complex<double>, 1, void, false, false>*) ()
   from /home/tayral/Work/TRIQS_1.6/install_gcc7/lib/python2.7/dist-packages/pytriqs/gf/singularities.so
#5  0x000000000041f6d3 in ?? ()
#6  0x00000000004b105e in PyArg_ParseTupleAndKeywords ()
#7  0x00007fffe255cf4e in singularities__make_tail_view_from_data(_object*, _object*, _object*) ()
   from /home/tayral/Work/TRIQS_1.6/install_gcc7/lib/python2.7/dist-packages/pytriqs/gf/singularities.so
```
I am wondering if this issue comes from yep itself, or if it reveals a subtle issue in make_tail_view_from_data... Any idea?
Thanks
Thomas

**Comment by Wentzell** [comment]
I could not reproduce your problem on my machine with current unstable branch. 
Does the problem persist for you? What operating system are you using?
