### ISSUE TITLE
[unstable] inverse(tail) broken in python since commit f33b237

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#484]
The recent Fix of #250 (f33b23747655edcee0262b7dd2470bffb6182385) lead to a test-failure in the cthyb single-site-bethe test with the error message

```
Traceback (most recent call last):
  File "/itp/MooseFS/AG-CMS/TRIQS/complex/new_debian/unstable/src/cthyb/test/python/single_site_bethe.py", line 44, in <module>
    S.solve(h_int=H, **p)
  File "/itp/MooseFS/AG-CMS/TRIQS/complex/new_debian/unstable/build/cthyb/python/cthyb/cthyb_solver.py", line 122, in solve
    fit_max_moment=fit_max_moment,fit_known_moments=fit_known_moments)
  File "/temp/AG-CMS/TRIQS/complex/new_debian/unstable/lib/python2.7/dist-packages/pytriqs/gf/tools.py", line 160, in tail_fit
    for name, g in G_iw: g.tail = inverse( inverse(G0_iw[name].tail) - Sigma_iw[name].tail )
  File "/temp/AG-CMS/TRIQS/complex/new_debian/unstable/lib/python2.7/dist-packages/pytriqs/gf/tools.py", line 35, in inverse
    assert hasattr(x,'inverse')
AssertionError
```

See also https://github.com/TRIQS/cthyb/issues/75

@mferrero Please review

**Comment by Wentzell** [comment]
Fixed by 4ed8d498298dac134383953d9b71490c4695e092
