### ISSUE TITLE
TRIQS_HDF5_data_scheme BrillouinZone is not recognized

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#517]
Dear all,

I am trying to store Green's function objects with MeshBrillouinZone meshes to file. Currently `triqs` breaks on reading the `.h5` file with the following error:
```
Warning : The TRIQS_HDF5_data_scheme BrillouinZone is not recognized. Returning as a group. Hint : did you forgot to import this python class ?
Traceback (most recent call last):
  File "test_bz_h5.py", line 28, in <module>
    ek_ref = s['ek']
  File "/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 222, in __getitem__
    return self.__getitem1__(key,self._reconstruct_python_objects)
  File "/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 266, in __getitem1__
    return r_class.__factory_from_dict__(key,values)
  File "/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 636, in __factory_from_dict__
    r = cls(name = name, **d)
  File "/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 203, in __init__
    delegate(self, **kw)
  File "/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 139, in delegate
    assert isinstance(mesh, all_meshes), "Mesh is unknown. Possible type of meshes are %s" % ', '.join(map(lambda m: m.__name__,all_meshes))
AssertionError: Mesh is unknown. Possible type of meshes are MeshProduct, MeshImTime, MeshImTimeLobattoCube, MeshReTime, MeshImFreq, MeshImTimeLobattoLine, MeshImTimePolySquare, MeshReFreq, MeshLegendre, MeshImTimePolyCube, MeshImTimeLobattoSquare, MeshImTimePolyLine, MeshCyclicLattice, MeshBrillouinZone
```
 Is this a typo somewhere in the mesh stating that the data scheme is `BrillouinZone` instead of `MeshBrillouinZone`?

Here is the test script that produces the error
```python
import numpy as np
from pytriqs.gf import *
from pytriqs.archive import HDFArchive
from pytriqs.lattice import BrillouinZone, BravaisLattice

bz = BrillouinZone(BravaisLattice([[1,0],[0,1]]))
bzmesh = MeshBrillouinZone(bz, n_k=10)

beta = 1.2345
fmesh = MeshImFreq(beta=beta, S='Fermion', n_max=10)
bmesh = MeshImFreq(beta=beta, S='Boson', n_max=5)
prodmesh = MeshProduct(bzmesh, bmesh, fmesh, fmesh)

ek = Gf(mesh=bzmesh, target_shape=[1, 1])
ek.data[:] = np.random.random(ek.data.shape)

chi = Gf(mesh=prodmesh, target_shape=[1, 1, 1, 1])
chi.data[:] = np.random.random(chi.data.shape)

filename = 'test_bz_h5.h5'

with HDFArchive(filename, 'w') as s:
    s['ek'] = ek
    s['chi'] = chi

with HDFArchive(filename, 'r') as s:
    ek_ref = s['ek']
    chi_ref = s['chi']

np.testing.assert_array_almost_equal(ek.data, ek_ref.data)
np.testing.assert_array_almost_equal(chi.data, chi_ref.data)
```
Could you please add it as a test? This is kind of blocking the `bse` and `tprf` work.

Cheers, H

**Comment by Wentzell** [comment]
This issue is resolved in the current master branch and the test was added.
