### ISSUE TITLE
Error multiplying 2 Gf's [unstable]

### ISSUE THREAD

**Issue by marcel-klett** [TRIQS/triqs#553]
I want to multiply two Greensfunctions but i get a strange Error (I checked in the stable Version and there no Error occurs)
```python
from pytriqs.gf import *

A1 = GfImFreq(indices = [0,1,2], beta = 10, statistic = "Boson", n_points = 100)
A2 = GfImFreq(indices = [0,1,2], beta = 10, statistic = "Boson", n_points = 100)

print A1.data.shape
print A2.data.shape

res = A1*A2

print res.data.shape
```

Error Message:
(199, 3, 3)
(199, 3, 3)
Traceback (most recent call last):
  File "multiplication.py", line 10, in <module>
    res = A1*A2
  File "/home/marcel/triqs_idx/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 564, in __mul__
    c.__imul__impl(y)
  File "/home/marcel/triqs_idx/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 511, in __imul__impl
    d_self =  rh(self.data)
  File "/home/marcel/triqs_idx/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 510, in <lambda>
    rh = lambda d : np.reshape(d, (reduce(mul, d.shape[:self.rank]),) + (d.shape[self.rank+1:]))
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1791 into shape (199,3)

Best regards
Marcel Klett

**Comment by Wentzell** [comment]
Fixed in ccc28f0
