### ISSUE TITLE
[doc] Not compiling on triqs/unstable with most recent cpp2py/master

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#566]
Dear All,

I am trying to build the current unstable with documentation and get a `cpp2rst` error:

```
[ 99%] Generating cpp2rst.log
Traceback (most recent call last):
  File "/Users/hstrand/apps/cpp2py/bin/c++2rst", line 41, in <module>
    W.run(args.output_directory)
  File "/Users/hstrand/apps/cpp2py/lib/python2.7/site-packages/cpp2rst/cpp2rst.py", line 174, in run
    r = render_fnt( doc_methods = docs[f_name], parent_class = None, f_name = f_name, f_overloads = f_overloads)
  File "/Users/hstrand/apps/cpp2py/lib/python2.7/site-packages/cpp2rst/render_fnt.py", line 75, in render_fnt
    R += make_synopsis_list(f_overloads, doc_methods) + '\n\n'
  File "/Users/hstrand/apps/cpp2py/lib/python2.7/site-packages/cpp2rst/synopsis.py", line 64, in make_synopsis_list
    signs = [ make_synopsis(x, d, decal) for x,d in zip(m_list,doc_methods)]
  File "/Users/hstrand/apps/cpp2py/lib/python2.7/site-packages/cpp2rst/synopsis.py", line 50, in make_synopsis
    params = [(p.type.spelling, p.spelling, CL.get_param_default_value(p)) for p in CL.get_params(m)]
  File "/Users/hstrand/apps/cpp2py/lib/python2.7/site-packages/cpp2py/clang_parser.py", line 121, in get_param_default_value
    assert len(sp) == 1 or len(sp) ==2
```

using triqs/unstable commit (`d747039d`) and cpp2py/master commit (`096a31c`)

Is this reproducible for anyone?

Best, Hugo

**Comment by Wentzell** [comment]
Please update your remotes, the latest commit 8e64e928 has fixed that!

**Comment by parcollet** [comment]
We fixed it this morning.
@Wentzell : did you push this ?

**Comment by HugoStrand** [comment]
Thank you Nils, it works perfectly with the latest commit 8e64e92.

I am sorry for causing confusion.
