### ISSUE TITLE
Tutorial example about local Green’s functions fails: tuple index out of range

### ISSUE THREAD

**Issue by yurivict** [TRIQS/triqs#593]
I'm trying to run this example: http://triqs.github.io/triqs/master/tour/green.html
It fails:
```
$ python2.7 ex.py 
Traceback (most recent call last):
  File "ex.py", line 11, in <module>
    g['s','s'] = inverse( Wilson(1.0) )
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 347, in __setitem__
    self[key] << val
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 380, in __lshift__
    self.copy_from (lazy_expressions.eval_expr_with_context(e_t, A2) )
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/lazy_expressions.py", line 99, in eval_expr_with_context
    return f (*map(lambda e:eval_expr_with_context(eval_term, e) , expr.childs[1:]) )
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/lazy_expressions.py", line 99, in <lambda>
    return f (*map(lambda e:eval_expr_with_context(eval_term, e) , expr.childs[1:]) )
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/lazy_expressions.py", line 95, in eval_expr_with_context
    if expr.tag == "T": return eval_term(expr.childs[0]) #eval the terminals
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 378, in e_t
    x(tmp)
  File "/usr/local/lib/python2.7/site-packages/pytriqs/gf/descriptors.py", line 122, in __call__
    Id = numpy.identity(G.target_shape[0],numpy.complex_)
IndexError: tuple index out of range
```

**Comment by Wentzell** [comment]
This example works well on the latest master and unstable.

Feel free to try it in the interactive [notebook](https://mybinder.org/v2/gh/TRIQS/binder/master) which is hosting an install of the latest master commit.
