### ISSUE TITLE
Tutorial example "Storing basic data types" fails: 'module' object has no attribute 'highlevel'

### ISSUE THREAD

**Issue by yurivict** [TRIQS/triqs#594]
This example: http://triqs.github.io/triqs/master/tutorials/hdf5/tut_ex1.html fails:
```
$ python2.7 hdf-save.py
Traceback (most recent call last):
  File "hdf-save.py", line 3, in <module>
    R = HDFArchive('myfile.h5', 'w') # Opens the file myfile.h5, in read/write mode
  File "/usr/local/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 395, in __init__
    HDFArchiveGroup.__init__(self,self,"")
  File "/usr/local/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 81, in __init__
    HDFArchiveGroupBasicLayer.__init__(self, parent, subpath)
  File "/usr/local/lib/python2.7/site-packages/pytriqs/archive/hdf_archive_basic_layer_h5py.py", line 32, in __init__
    assert type(self._group) in [h5py.highlevel.Group,h5py.highlevel.File], "Internal error"
AttributeError: 'module' object has no attribute 'highlevel'
```

**Comment by Wentzell** [comment]
This is fixed by #667
