### ISSUE TITLE
Bug in BlockGf, make robust filter for gf_struct?

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#672]
Hi,

I am trying to make a `BlockGf` from a mesh and a `gf_struct` but the `BlockGf` constructor is fragile when it comes to the format of `gf_struct`. It seems not to be able to handle ndarrays, only lists. 

That would be fine if one would get an informative error, but no. Can we write a little filter for `gf_structs` that converts anything iterable to the standard list of lists format and use it inside things taking gf_struct as argument? Like this:
```python
filter_gf_struct = lambda gf_struct : [ [bidx, list(idxs)] for (bidx, idxs) in gf_struct ]
```
Here is a breaking example:
```python

import numpy as np
from pytriqs.gf import MeshImTime, BlockGf

norb, beta, ntau = 3, 10., 1000

#orb_idxs = list(np.arange(norb)) # Works!
orb_idxs = np.arange(norb) # ndarray gives a non-informative error

spin_idxs = ['up', 'do']
gf_struct = [ [spin_idx, orb_idxs] for spin_idx in spin_idxs ]

mesh = MeshImTime(beta, 'Fermion', ntau)

G_tau = BlockGf(mesh=mesh, gf_struct=gf_struct)

for block_name, g_tau in G_tau:
    print block_name
    print g_tau.data.shape
```
which gives the not so informative error (that will keep you debugging for some time...)
```
Traceback (most recent call last):
  File "bug_blockgf_gf_struct.py", line 15, in <module>
    G_tau = BlockGf(mesh=mesh, gf_struct=gf_struct)
  File "/Users/hugstr/apps/triqs_unstable/lib/python2.7/site-packages/pytriqs/gf/block_gf.py", line 79, in __init__
    GFlist.append(Gf(mesh=kwargs['mesh'], target_shape=[len(idx_lst)]*kwargs['target_rank'], name='G_%s'%bl, indices=[idx_lst]*kwargs['target_rank']))
  File "/Users/hugstr/apps/triqs_unstable/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 192, in __init__
    delegate(self, **kw)
  File "/Users/hugstr/apps/triqs_unstable/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 174, in delegate
    assert (d == i), "Indices are of incorrect size. Data size is %s while indices size is %s"%(d,i)
AssertionError: Indices are of incorrect size. Data size is (3, 3) while indices size is (2, 2)
```

**Comment by Wentzell** [comment]
This is now fixed on TRIQS/unstable, where `gf_struct` should be a list of pairs of block-name (str) and block-size (int).

The error message now reads

```
Traceback (most recent call last):
  File "issue672.py", line 14, in <module>
    G_tau = BlockGf(mesh=mesh, gf_struct=gf_struct)
  File "/mnt/home/wentzell/opt/triqs/lib/python3.8/site-packages/triqs/gf/block_gf.py", line 95, in __init__
    assert isinstance(bl_size, (int, np.integer)), "gf_struct should be a list of pairs of bl_name (str) and bl_size (int)"
AssertionError: gf_struct should be a list of pairs of bl_name (str) and bl_size (int)
```
