### ISSUE TITLE
Issue with Monte Carlo Error : the rate ((nan,nan)) is not finite in move Shift one operator

### ISSUE THREAD

**Issue by hrishitbanerjee** [TRIQS/triqs#711]
Hii,
I am getting this particular error while doing calculations with certain systems like LaTiO3 and LaMnO3. The calculations are stopping after a few warmup steps only.
Can anyone comment on why this is happening and how it can be solved?
Thanks and best regards
Hrishit.

Traceback (most recent call last):
  File "LTO-ortho.py", line 144, in <module>
    S.solve(h_int = H, **p)
  File "/temp/AG-CMS/TRIQS/2.1/complex/lib/python2.7/site-packages/triqs_cthyb/solver.py", line 130, in solve
    solve_status = SolverCore.solve(self, **params_kw)
RuntimeError: .. Error occurred at Tue May 21 15:23:19 2019

.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at /temp/AG-CMS/TRIQS/2.1/complex/include/triqs/mc_tools/./mc_move_set.hpp : 205

Monte Carlo Error : the rate ((nan,nan)) is not finite in move Shift one operator
.. Error occurred on node 0

**Comment by Wentzell** [comment]
Moving this to the TRIQS/cthyb issue list.
