### ISSUE TITLE
tests FAILED

### ISSUE THREAD

**Issue by hungtranvn** [TRIQS/triqs#759]
Dear all,

I am trying to install TRIQS 2.2.1. Everything about the building process is ok but the testing process met a problem as follows.

```
95% tests passed, 10 tests failed out of 208

Total Test time (real) = 363.72 sec

The following tests FAILED:
        180 - py_g_tau_mul (Failed)
        181 - py_dos (Failed)
        189 - py_bug_tight_binding (Failed)
        190 - py_bug_bcast_mesh (Failed)
        194 - py_block_matrix (Failed)
        195 - py_gf_tensor_valued (Failed)
        197 - py_histogram_bcast (Failed)
        198 - py_brillouin_zone (Failed)
        199 - py_multivar (Failed)
        201 - py_g_k_om (Failed)
Errors while running CTest
make: *** [Makefile:97: test] Error 8
```

Does anyone know the cause of this issue?

Thanks in advance!

**Comment by the-hampel** [comment]
Hi, 
Without the complete error log this is difficult to answer. Maybe some MPI problem. Is this a local installation or on the cluster? Did you manually build triqs? 

Could you please provide the full error output of one of the tests? You can also run each test manually and paste here the output. Go into the build directory where you ran the `make test` command and run for example:
```
ctest -V -R py_g_tau_mul
```

Please compare also a few tests, if they all fail with the same problem.

Best,
Alex

**Comment by hungtranvn** [comment]
Dear Alex,

This is error log file 
https://gist.github.com/hungtranvn/bb466e4f4b5c39c024d39ca909cb236c

I built TRIQS on my personal computer (fedora 30) following triqs instructions (https://triqs.github.io/triqs/latest/install.html). 

I run each failed test manually and received the same error message:
```
[hungtran@localhost triqs.build]$ ctest -V -R py_g_k_om 
UpdateCTestConfiguration  from :/home/hungtran/SRC/triqs/triqs.build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/hungtran/SRC/triqs/triqs.build/DartConfiguration.tcl
Test project /home/hungtran/SRC/triqs/triqs.build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 201
    Start 201: py_g_k_om

201: Test command: /usr/bin/python "/home/hungtran/SRC/triqs/triqs.src/test/pytriqs/gf_multivar/g_k_om.py"
201: Environment variables: 
201:  PYTHONPATH=/home/hungtran/SRC/triqs/triqs.build:/home/hungtran/SRC/triqs/triqs.build/cpp2py:./:
201: Test timeout computed to be: 10000000
201: Traceback (most recent call last):
201:   File "/home/hungtran/SRC/triqs/triqs.src/test/pytriqs/gf_multivar/g_k_om.py", line 2, in <module>
201:     from pytriqs.lattice import *
201:   File "/home/hungtran/SRC/triqs/triqs.build/pytriqs/lattice/tight_binding.py", line 32, in <module>
201:     from pytriqs.dos import DOS
201:   File "/home/hungtran/SRC/triqs/triqs.build/pytriqs/dos/__init__.py", line 24, in <module>
201:     from hilbert_transform import HilbertTransform
201:   File "/home/hungtran/SRC/triqs/triqs.build/pytriqs/dos/hilbert_transform.py", line 27, in <module>
201:     import pytriqs.utility.mpi as mpi
201:   File "/home/hungtran/SRC/triqs/triqs.build/pytriqs/utility/mpi.py", line 22, in <module>
201:     from mpi_mpi4py import *
201:   File "/home/hungtran/SRC/triqs/triqs.build/pytriqs/utility/mpi_mpi4py.py", line 27, in <module>
201:     from mpi4py import MPI
201: ImportError: /home/hungtran/.local/lib/python2.7/site-packages/mpi4py/MPI.so: undefined symbol: ompi_mpi_logical8
1/1 Test #201: py_g_k_om ........................***Failed    0.25 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.27 sec

The following tests FAILED:
        201 - py_g_k_om (Failed)
Errors while running CTest
```
Probably MPI problem. Do you know how to solve this problem?
Many thanks!

**Comment by hungtranvn** [comment]
Dear Alex,

The problem related to mpi.
I solved it by reinstalling mpi4py
```
pip2 uninstall mpi4py
pip2 install --no-cache-dir mpi4py
```
This issue is closed.
