### ISSUE TITLE
Error building triqs@unstable with documentation with clang version 11.0.0-2~ubuntu20.04.1

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#813]
Dear Triqs devs,

I have successfully built `triqs/unstable` (9bd8c2bf) without documentation on my ubuntu 20.04.1 with clang version 11.0.0 and libc++.

When enabling the build of the documentation I get an error in `c++2rst` of a missing header

```
Scanning dependencies of target nda_docs_cpp2rst
Welcome to the C++ doc generator !
Parsing the C++ file (may take a few seconds) ...
Traceback (most recent call last):
  File "/home/hugstr/dev/triqs/cbuild/deps/Cpp2Py/bin/c++2rst", line 33, in <module>
    W = Cpp2Rst(filename = args.filename,
  File "/home/hugstr/dev/triqs/cbuild/deps/Cpp2Py/cpp2rst/cpp2rst.py", line 78, in __init__
    self.root = CL.parse(filename, compiler_options, includes, system_includes, libclang_location, parse_all_comments)
  File "/home/hugstr/dev/triqs/cbuild/deps/Cpp2Py/cpp2py/clang_parser.py", line 444, in parse
    raise RuntimeError(s + "\n... Your code must compile before using clang-parser !")
RuntimeError: Clang reports the following errors in parsing
 file /home/hugstr/dev/triqs/cbuild/deps/nda_src/c++/nda/stdutil/concepts.hpp line 18 col 10
'concepts' file not found
... Your code must compile before using clang-parser !
make[2]: *** [deps/nda/doc/CMakeFiles/nda_docs_cpp2rst.dir/build.make:58: nda_docs_cpp2rst] Error 1
make[1]: *** [CMakeFiles/Makefile2:4702: deps/nda/doc/CMakeFiles/nda_docs_cpp2rst.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

probably the include paths from CMake are not successfully forwarded to `c++2rst`?

Is there some environment variable setup that I can do to fix this?

Best, Hugo

**Comment by Wentzell** [comment]
Dear @HugoStrand,

Have you installed, alongside `clang-11` the apt packages `libclang-11-dev` and `python3-clang-11`?

**Comment by Wentzell** [comment]
Please also have a look at our Ubuntu focal base image which we use to compile the doc on our jenkins CI.
https://github.com/TRIQS/triqs/blob/unstable/packaging/Dockerfile.ubuntu-clang
This setup is using llvm-12 instead of 11 and uses the https://apt.llvm.org/ packages.

**Comment by HugoStrand** [comment]
Dear Nils,

Yes, I have `clang-11`, `libclang-11-dev` and `python3-clang-11` installed
```
$ apt list --installed | grep clang
clang-11/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed]
libclang-11-dev/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed,automatic]
libclang-common-11-dev/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed,automatic]
libclang-cpp11/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed,automatic]
libclang1-11/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed,automatic]
python3-clang-11/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed]
```
as well as the `libc++` packages
```
$ apt list --installed | grep libc\+\+
libc++-11-dev/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed]
libc++1-11/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed,automatic]
libc++abi-11-dev/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed]
libc++abi1-11/focal-updates,now 1:11.0.0-2~ubuntu20.04.1 amd64 [installed,automatic]
```

We had this kind of errors within the `c++2py` tools before, since they call the compilers outside of the scope of `CMake` and hence do not get the same path setup automatically.

Since I am able to build `triqs/unstable` without the documentation the `<concepts>` header is present on my system ( located at `/usr/lib/llvm-11/include/c++/v1/concepts` ). 

How can I tell `c++2rst` where to look for the header?

Looking at the docker setup for the CI it looks as if you are using `clang-12` throughout (not only `llvm-12`). 

Is `clang-12` a requirement for building the documentation?

Best, Hugo

**Comment by Wentzell** [comment]
Hey Hugo,

clang-12 is not a requirement for the doc. clang-11 should be sufficient.

Can you please provide the `c++2rst ...` command that is executed?
You should see it in the final step when you execute `make -j1 VERBOSE=1 nda_docs_cpp2rst`

**Comment by Wentzell** [comment]
Closing this due to inactivity, reopen if the issue persists.
